# Generated by Django 5.2.3 on 2025-06-15 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bidang', models.CharField(max_length=100)),
                ('deskripsi_bidang', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_event', models.CharField(max_length=200)),
                ('deskripsi_event', models.TextField()),
                ('tanggal_mulai', models.DateTimeField()),
                ('lokasi', models.CharField(max_length=200)),
                ('poster_event', models.ImageField(upload_to='event_posters/')),
                ('status', models.CharField(choices=[('Akan Datang', 'Akan Datang'), ('Selesai', 'Selesai')], default='Akan Datang', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('jabatan', models.CharField(max_length=50)),
                ('foto_profil', models.ImageField(upload_to='anggota/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('angkatan', models.IntegerField()),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota', to='core.bidang')),
            ],
        ),
        migrations.CreateModel(
            name='Dokumentasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_dokumentasi', models.CharField(max_length=200)),
                ('deskripsi_singkat', models.TextField()),
                ('link_gdrive', models.URLField()),
                ('foto_unggulan', models.ImageField(upload_to='dokumentasi/')),
                ('event_terkait', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('konten', models.TextField()),
                ('tanggal_publikasi', models.DateTimeField(auto_now_add=True)),
                ('tipe', models.CharField(choices=[('Pemberitahuan', 'Pemberitahuan'), ('Pengumuman', 'Pengumuman')], default='Pemberitahuan', max_length=20)),
                ('penulis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
